configured_endpoints: 8
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/dizzzmas-Dizzzmas-sy3cfe%2Fsst-url-shortener-9b7a51bdb1d7bd087b9b5ab07555a5a89182ed7c758661ad2d0a675244d53768.yml
